### ISSUE TITLE
Date Picker is overlapping with patient details 

### ISSUE THREAD

**Issue by Balaji3049** [someshkar/covid19india-network#36]
![Screenshot_2020-03-24-23-50-52-79](https://user-images.githubusercontent.com/10631319/77462969-de91cb80-6e2a-11ea-8592-3e5cddc6a039.png)

**Comment by someshkar** [comment]
Yeah, we've decided to just hide the `date-picker` on mobile, for now. I'll get back to it later, or maybe someone could make a PR to fix it? Closing this for now.
