### ISSUE TITLE
India map delhi is not available 

### ISSUE THREAD

**Issue by dhruvaggarwal2709** [someshkar/covid19india-network#37]
Show result by click on map. Delhi is not availbe.

**Comment by someshkar** [comment]
What exactly do you mean should happen? Please elaborate.

**Comment by dhruvaggarwal2709** [comment]
There is a map on page screen where we can interact with to get state wise result.
Delhi is not there on the map.



On 25 Mar 2020 2:58 am, Somesh Kar <notifications@github.com> wrote:

What exactly do you mean should happen? Please elaborate.

**Comment by vrajeshkanna** [comment]
@dhruvaggarwal2709 Please raise this issue in the respective repo https://github.com/covid19india/covid19india-react
