### ISSUE TITLE
Crash on non-patient node selection

### ISSUE THREAD

**Issue by SahajR** [someshkar/covid19india-network#38]
The patient data is changed when a node is selected. Currently, there is a crash when a node other than a patient (like city) is selected.

Also, we need a better handler for different node selections.

**Comment by someshkar** [comment]
I think you're referring to the crash on the 'City' filter? Yes, that has to be fixed, but I'm fairly sure it's an issue with the data, and I've taken it up with the Ops team on Telegram.

**Comment by SahajR** [comment]
I pushed a fix for this
