### ISSUE TITLE
Search by Patient number is not working (Machine:Macbook Browser: Chrome)

### ISSUE THREAD

**Issue by anil-pandey-mpf** [someshkar/covid19india-network#46]
Search by Patient number is not working.
Machine: Macbook, chrome 
Enter any patient number on search bar and hit enter. It will not return any result.
![image](https://user-images.githubusercontent.com/26223552/77516391-9e5a3980-6e7a-11ea-8af8-b6e7cd036d49.png)

**Comment by hasannaqi9** [comment]
In chrome browser the patient number without 'P' is working and with P it is not working ex:
P1 --not working
1 -- working

**Comment by anil-pandey-mpf** [comment]
better would be to provide some kind of hint. thanks

**Comment by sibeshkar** [comment]
Fixed in https://github.com/someshkar/covid19india-network/pull/53
