### ISSUE TITLE
Title Bar Blinking

### ISSUE THREAD

**Issue by Kalibaba-Pro** [someshkar/covid19india-network#58]
When ever it's Go One to Another Options   Like:- Home Bottone to CLUSTERS it's automatically Change it's Size. also Blinking.

Thank You. #Kalibaba-Pro
![Screenshot (85)](https://user-images.githubusercontent.com/62648401/77537040-7216db00-6ec3-11ea-8b9a-5caf46c25cb4.png)
![Screenshot (86)](https://user-images.githubusercontent.com/62648401/77537068-7b07ac80-6ec3-11ea-8a68-b0d82ba958b5.png)

**Comment by SahajR** [comment]
This is more relevant on the main website: https://github.com/covid19india/covid19india-react
