### ISSUE TITLE
Add ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by gshanbhag525** [someshkar/covid19india-network#61]
I would like to add an issue template folder with pull request template bug_report_template.md and feature_request_template.md.

# Screenshots

## Bug Report
![github_bugreport](https://user-images.githubusercontent.com/17478096/77562440-085bf880-6ee6-11ea-89bc-b75b93b04b60.png)

## Feature Request
![github_featurere](https://user-images.githubusercontent.com/17478096/77562517-1f024f80-6ee6-11ea-89b9-0ceebed40ba2.png)

## Pull Request
![github_pullreq](https://user-images.githubusercontent.com/17478096/77562552-29bce480-6ee6-11ea-8421-03acfe5d1a3c.png)

**Comment by sibeshkar** [comment]
Sure, feel free to make a PR with this and code of conduct.
