### ISSUE TITLE
Patients Tabular Representation

### ISSUE THREAD

**Issue by swapnilsanu** [someshkar/covid19india-network#62]
Below are my observation regarding below. These are just enhancements :-

1. A tabular representation of patients can be more convenient, as we could then provide filters based on <b>city/state/age/travel history</b>

2. We could think of showing all the <b>Related Patients</b> together.. Related as in (Same Family) in drill down of that row maybe. So, when a person sees all the Related Patients together as it's won't create panic as the first thing we are currently seeing is numbers.

3. The footer could be adjusted for a better view in <b>mobile</b> very less space remains in patients view.

I would like to Thank You people for such an important work you people have done for Society in such short notice.

Hats off...Respect....Jai Hind.

**Comment by sibeshkar** [comment]
You can check that out at [http://portal.covid19india.org](http://portal.covid19india.org)
